<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // ===== DATABASE COMPUTER - REAL PRODUCTS ===== //
        // Official products from Computer Store Pontianak
        // Gold Merchant Tokopedia & Shopee Mall | 12+ Bank Partnerships

        // === SMARTPHONES (Category ID: 1) === //
        
        // iPhone Products - Original products with TAM Warranty
        Product::create([
            'name' => 'iPhone 15 Pro Max 256GB',
            'brand' => 'Apple',
            'description' => 'iPhone 15 Pro Max dengan chipset A17 Pro terbaru dan kamera profesional 48MP. Garansi Resmi TAM 1 Tahun. Cicilan 0% tersedia dari 12+ bank partner kami (BCA, Mandiri, BNI, BRI, CIMB, dll).',
            'price' => 24999000,
            'sku' => 'DB-IP15PM-256',
            'image_url' => 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&q=80&w=800',
            'image_thumbnail_url' => 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&q=80&w=400',
            'stock' => 2,
            'specifications' => [
                'product_number' => 'MU793ZP/A',
                'processor' => 'Apple A17 Pro Chip',
                'gpu' => '6-core GPU',
                'storage' => '256GB',
                'display' => '6.7" Super Retina XDR with ProMotion (120Hz)',
                'camera' => '48MP Main + 12MP Ultra Wide + 12MP Telephoto',
                'wireless_connectivity' => 'WiFi 6E (802.11ax), Bluetooth 5.3, 5G Sub-6GHz',
                'dimensions_width' => '7.69',
                'dimensions_depth' => '0.83',
                'dimensions_height' => '15.98',
                'weight' => '221g',
                'webcam' => '12MP TrueDepth Front Camera',
                'audio' => 'Stereo speakers, Spatial Audio, Dolby Atmos',
                'operating_system' => 'iOS 17',
                'warranty' => 'Garansi Resmi TAM 1 Tahun',
                'condition' => 'new',
                'extras' => 'Cicilan 0% dari 12+ bank • Bonus: Tempered Glass + Case',
            ],
            'category_id' => 1,
        ]);

        Product::create([
            'name' => 'iPhone 15 128GB',
            'brand' => 'Apple',
            'description' => 'iPhone 15 dengan chipset A16 Bionic dan Dynamic Island. Garansi Resmi TAM 1 Tahun. Cicilan 0% tersedia dari 12+ bank partner. Best seller untuk produktivitas dan gaming.',
            'price' => 11249000,
            'sku' => 'DB-IP15-128',
            'image_url' => 'https://images.unsplash.com/photo-1696446701796-da61225697cc?auto=format&fit=crop&q=80&w=800',
            'image_thumbnail_url' => 'https://images.unsplash.com/photo-1696446701796-da61225697cc?auto=format&fit=crop&q=80&w=400',
            'stock' => 3,
            'specifications' => [
                'product_number' => 'MTP13ZP/A',
                'processor' => 'Apple A16 Bionic Chip',
                'gpu' => '5-core GPU',
                'storage' => '128GB',
                'display' => '6.1" Super Retina XDR',
                'camera' => '48MP Main + 12MP Ultra Wide',
                'wireless_connectivity' => 'WiFi 6 (802.11ax), Bluetooth 5.3, 5G',
                'dimensions_width' => '7.15',
                'dimensions_depth' => '0.78',
                'dimensions_height' => '14.78',
                'weight' => '171g',
                'webcam' => '12MP TrueDepth Camera',
                'audio' => 'Stereo speakers, Spatial Audio',
                'operating_system' => 'iOS 17',
                'warranty' => 'Garansi Resmi TAM 1 Tahun',
                'condition' => 'new',
                'extras' => 'Cicilan 0% dari 12+ bank • Bonus: Tempered Glass + Case',
            ],
            'category_id' => 1,
        ]);

        Product::create([
            'name' => 'iPhone 13 128GB',
            'brand' => 'Apple',
            'description' => 'iPhone 13 dengan chipset A15 Bionic, pilihan terbaik untuk pelajar dan mahasiswa. Garansi Resmi TAM 1 Tahun. Cicilan 0% tersedia. Value for money terbaik di kelasnya.',
            'price' => 8249000,
            'sku' => 'DB-IP13-128',
            'image_url' => 'https://images.unsplash.com/photo-1632661674596-df8be070a5c5?auto=format&fit=crop&q=80&w=800',
            'image_thumbnail_url' => 'https://images.unsplash.com/photo-1632661674596-df8be070a5c5?auto=format&fit=crop&q=80&w=400',
            'stock' => 2,
            'specifications' => [
                'product_number' => 'MLPG3ZP/A',
                'processor' => 'Apple A15 Bionic Chip',
                'gpu' => '4-core GPU',
                'storage' => '128GB',
                'display' => '6.1" Super Retina XDR',
                'camera' => '12MP Dual Camera System',
                'wireless_connectivity' => 'WiFi 6, Bluetooth 5.0, 5G',
                'dimensions_width' => '7.15',
                'dimensions_depth' => '0.77',
                'dimensions_height' => '14.67',
                'weight' => '174g',
                'webcam' => '12MP TrueDepth Camera',
                'audio' => 'Stereo speakers',
                'operating_system' => 'iOS 15 (upgradeable)',
                'warranty' => 'Garansi Resmi TAM 1 Tahun',
                'condition' => 'new',
                'extras' => 'Best seller pelajar & mahasiswa • Cicilan 0% tersedia',
            ],
            'category_id' => 1,
        ]);

        // === LAPTOPS (Category ID: 2) === //
        
        // Gaming & High-Performance Laptops
        Product::create([
            'name' => 'Asus TUF Gaming A15 Ryzen 7 RTX 4060',
            'brand' => 'ASUS',
            'description' => 'Laptop gaming powerful dengan Ryzen 7 dan RTX 4060 untuk gaming dan content creation. Display 144Hz untuk pengalaman gaming smooth. Garansi toko 3 bulan. Bonus lengkap!',
            'price' => 15100000,
            'sku' => 'DB-ASUS-TUF-A15',
            'image_url' => 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&q=80&w=800',
            'image_thumbnail_url' => 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&q=80&w=400',
            'stock' => 1,
            'specifications' => [
                'product_number' => 'FA507NU-LP045W',
                'processor' => 'AMD Ryzen 7-7735HS',
                'chipset' => 'AMD Rembrandt',
                'gpu' => 'NVIDIA GeForce RTX 4060 8GB',
                'ram' => '16GB DDR5',
                'storage' => '512GB NVMe SSD',
                'display' => '15.6" FHD (1920x1080) 144Hz',
                'keyboard' => 'RGB Backlit',
                'optical_drive' => 'None',
                'wireless_connectivity' => 'WiFi 6 (802.11ax), Bluetooth 5.2',
                'expansion_slots' => '1x M.2 NVMe slot (occupied), 2x DDR5 SO-DIMM slots',
                'external_ports' => '1x USB 3.2 Gen 2 Type-C, 3x USB 3.2 Gen 1 Type-A, 1x HDMI 2.1, 1x RJ45 LAN, 1x 3.5mm Audio Jack',
                'dimensions_width' => '35.4',
                'dimensions_depth' => '25.1',
                'dimensions_height' => '2.24',
                'weight' => '2.2kg',
                'battery' => '90Wh, up to 6 hours',
                'power_supply_type' => '200W AC Adapter',
                'webcam' => '720p HD Camera',
                'audio' => 'DTS:X Ultra, AI Noise Cancellation',
                'operating_system' => 'Windows 11 Home',
                'software_included' => 'Armoury Crate, Xbox Game Pass Trial (3 months)',
                'warranty' => 'Garansi toko 3 bulan',
                'condition' => 'used-excellent',
                'extras' => 'Tas Laptop + Mouse Wireless + Cooling Pad',
            ],
            'category_id' => 2,
        ]);

        Product::create([
            'name' => 'Lenovo IdeaPad Gaming 3 Ryzen 5 RTX 3050',
            'brand' => 'Lenovo',
            'description' => 'Gaming laptop value for money dengan performa solid untuk gaming AAA dan editing. Display 120Hz untuk visual smooth. Perfect untuk gamers pemula. Bonus lengkap!',
            'price' => 9500000,
            'sku' => 'DB-LENOVO-GAMING3',
            'image_url' => 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&q=80&w=800',
            'image_thumbnail_url' => 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&q=80&w=400',
            'stock' => 1,
            'specifications' => [
                'product_number' => '82K201DXID',
                'processor' => 'AMD Ryzen 5-5600H',
                'chipset' => 'AMD Cezanne',
                'gpu' => 'NVIDIA GeForce RTX 3050 4GB',
                'ram' => '8GB DDR4 (upgradeable to 16GB)',
                'storage' => '512GB NVMe SSD',
                'display' => '15.6" FHD (1920x1080) 120Hz',
                'keyboard' => 'Backlit',
                'optical_drive' => 'None',
                'wireless_connectivity' => 'WiFi 6 (802.11ax), Bluetooth 5.1',
                'expansion_slots' => '1x M.2 NVMe, 2x DDR4 SO-DIMM (1 free)',
                'external_ports' => '1x USB-C 3.2 Gen 2, 2x USB-A 3.2, 1x USB-A 2.0, 1x HDMI 2.0, 1x RJ45, 1x Audio Jack',
                'dimensions_width' => '35.94',
                'dimensions_depth' => '25.19',
                'dimensions_height' => '2.49',
                'weight' => '2.25kg',
                'battery' => '60Wh, up to 5 hours',
                'power_supply_type' => '135W AC Adapter',
                'webcam' => '720p with Privacy Shutter',
                'audio' => 'Nahimic Audio, Stereo 2W speakers',
                'operating_system' => 'Windows 11 Home',
                'software_included' => 'Lenovo Vantage, Office Trial',
                'warranty' => 'Garansi toko 3 bulan',
                'condition' => 'used-excellent',
                'extras' => 'Tas Laptop + Mouse Wireless',
            ],
            'category_id' => 2,
        ]);

        // Student & Office Laptops
        Product::create([
            'name' => 'Asus Vivobook 14 Core i5 Gen 11',
            'brand' => 'ASUS',
            'description' => 'Laptop student & office yang ringan dan powerful. Cocok untuk kuliah online, kerja kantoran, dan multimedia. Display FHD untuk visual jernih. Garansi toko 3 bulan.',
            'price' => 6500000,
            'sku' => 'DB-ASUS-VIVO14-I5',
            'image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&q=80&w=800',
            'image_thumbnail_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&q=80&w=400',
            'stock' => 2,
            'specifications' => [
                'product_number' => 'X413EA-EB551',
                'processor' => 'Intel Core i5-1135G7 (Gen 11)',
                'chipset' => 'Intel Tiger Lake PCH',
                'gpu' => 'Intel Iris Xe Graphics',
                'ram' => '8GB DDR4',
                'storage' => '512GB NVMe SSD',
                'display' => '14" FHD (1920x1080)',
                'wireless_connectivity' => 'WiFi 5 (802.11ac), Bluetooth 4.2',
                'external_ports' => '1x USB-C 3.2, 2x USB-A 3.2, 1x USB-A 2.0, 1x HDMI 1.4, 1x MicroSD Reader, 1x Audio Jack',
                'dimensions_width' => '32.54',
                'dimensions_depth' => '21.62',
                'dimensions_height' => '1.79',
                'weight' => '1.6kg',
                'battery' => '42Wh, up to 7 hours',
                'power_supply_type' => '45W USB-C Power Adapter',
                'webcam' => '720p HD Camera',
                'audio' => 'SonicMaster stereo speakers',
                'operating_system' => 'Windows 11 Home',
                'warranty' => 'Garansi toko 3 bulan',
                'condition' => 'used-very-good',
                'extras' => 'Tas Laptop + Mouse Wireless',
            ],
            'category_id' => 2,
        ]);

        Product::create([
            'name' => 'HP 14s Core i3 Gen 10',
            'brand' => 'HP',
            'description' => 'Laptop entry-level dengan performa reliable untuk tugas sehari-hari. Perfect untuk pelajar SMA/mahasiswa. Design slim dan elegan. Harga terjangkau dengan kualitas terjamin.',
            'price' => 4500000,
            'sku' => 'DB-HP-14S-I3',
            'image_url' => 'https://images.unsplash.com/photo-1484788984921-03950022c9ef?auto=format&fit=crop&q=80&w=800',
            'image_thumbnail_url' => 'https://images.unsplash.com/photo-1484788984921-03950022c9ef?auto=format&fit=crop&q=80&w=400',
            'stock' => 2,
            'specifications' => [
                'product_number' => '14s-dq2001TU',
                'processor' => 'Intel Core i3-1005G1 (Gen 10)',
                'gpu' => 'Intel UHD Graphics',
                'ram' => '4GB DDR4 (upgradeable to 16GB)',
                'storage' => '256GB SSD',
                'display' => '14" HD (1366x768)',
                'wireless_connectivity' => 'WiFi 5, Bluetooth 4.2',
                'external_ports' => '2x USB-A 3.1, 1x USB-A 2.0, 1x HDMI 1.4, 1x Audio Jack',
                'dimensions_width' => '32.4',
                'dimensions_depth' => '22.5',
                'dimensions_height' => '1.79',
                'weight' => '1.5kg',
                'battery' => '41Wh, up to 6 hours',
                'power_supply_type' => '45W AC Adapter',
                'operating_system' => 'Windows 11 Home',
                'warranty' => 'Garansi toko 3 bulan',
                'condition' => 'used-good',
                'extras' => 'Tas Laptop + Mouse',
            ],
            'category_id' => 2,
        ]);

        Product::create([
            'name' => 'Lenovo ThinkPad L14 Core i5 Gen 10',
            'brand' => 'Lenovo',
            'description' => 'Business laptop profesional dengan build quality premium. Keyboard ThinkPad legendaris untuk produktivitas tinggi. Cocok untuk profesional dan pengusaha.',
            'price' => 7200000,
            'sku' => 'DB-LENOVO-THINKPAD-L14',
            'image_url' => 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&q=80&w=800',
            'image_thumbnail_url' => 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&q=80&w=400',
            'stock' => 1,
            'specifications' => [
                'product_number' => '20U5S02F00',
                'processor' => 'Intel Core i5-10210U (Gen 10)',
                'chipset' => 'Intel Comet Lake PCH',
                'gpu' => 'Intel UHD Graphics',
                'ram' => '8GB DDR4',
                'storage' => '256GB NVMe SSD',
                'display' => '14" FHD (1920x1080) IPS',
                'optical_drive' => 'Optional external',
                'wireless_connectivity' => 'WiFi 6 (802.11ax), Bluetooth 5.1',
                'expansion_slots' => '1x M.2 NVMe, 2x DDR4 SO-DIMM (1 free)',
                'external_ports' => '2x USB-A 3.2, 1x USB-C 3.2, 1x USB-C Thunderbolt 3, 1x HDMI 1.4, 1x RJ45, 1x Audio Jack, 1x microSD Reader',
                'dimensions_width' => '32.8',
                'dimensions_depth' => '23.5',
                'dimensions_height' => '2.0',
                'weight' => '1.61kg',
                'power_supply_type' => '65W USB-C Adapter (compatible with Thunderbolt dock)',
                'webcam' => '720p with ThinkShutter Privacy',
                'audio' => 'Dolby Audio, Dual Speakers',
                'operating_system' => 'Windows 11 Pro',
                'software_included' => 'Lenovo Vantage, Microsoft Office Trial',
                'warranty' => 'Garansi toko 3 bulan',
                'condition' => 'used-excellent',
                'features' => 'Fingerprint Reader • Webcam Privacy Shutter',
                'extras' => 'Tas Laptop + Mouse Wireless + Original Charger',
            ],
            'category_id' => 2,
        ]);

        // Premium 2-in-1 Convertible
        Product::create([
            'name' => 'HP Envy X360 13-AY1002AU',
            'brand' => 'HP',
            'description' => 'Premium 2-in-1 convertible laptop dengan layar sentuh 13.3 inch dan AMD Ryzen 5. Sempurna untuk profesional yang membutuhkan portabilitas dan performa. Layar FHD touchscreen 400 nits dengan Gorilla Glass. Build quality premium dengan audio Bang & Olufsen. Garansi toko 3 bulan.',
            'price' => 12000000,
            'sku' => 'DB-HP-ENVY-X360',
            'image_url' => 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&q=80&w=800',
            'image_thumbnail_url' => 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&q=80&w=400',
            'stock' => 3,
            'specifications' => [
                'product_number' => '4Y7J1PA',
                'processor' => 'AMD Ryzen™ 5 5600U (up to 4.2 GHz, 6 cores, 12 threads)',
                'chipset' => 'AMD Integrated SoC',
                'gpu' => 'AMD Radeon™ Graphics',
                'ram' => '8 GB DDR4-3200 MHz (onboard)',
                'storage' => '256 GB PCIe® NVMe™ M.2 SSD',
                'display' => '13.3" FHD (1920x1080) Touchscreen IPS, Gorilla Glass, 400 nits, 100% sRGB',
                'keyboard' => 'Backlit keyboard',
                'optical_drive' => 'None',
                'wireless_connectivity' => 'Realtek Wi-Fi 6™ (2×2) and Bluetooth® 5.2',
                'expansion_slots' => '1x microSD card reader',
                'external_ports' => '1x USB-C 10Gbps (PD, DP 1.4), 2x USB-A 5Gbps, 1x Audio Jack',
                'dimensions_width' => '30.66',
                'dimensions_depth' => '19.46',
                'dimensions_height' => '1.65',
                'weight' => '1.3kg',
                'battery' => 'Up to 13 hours',
                'power_supply_type' => '65W AC Adapter, 51Wh Li-ion polymer',
                'webcam' => '720p HD with Privacy Shutter, Dual Microphones',
                'audio' => 'Bang & Olufsen, Dual Speakers, HP Audio Boost',
                'operating_system' => 'Windows 11 Home',
                'software_included' => 'Microsoft Office, VLC Player, Adobe Reader, McAfee LiveSafe™',
                'warranty' => 'Garansi toko 3 bulan',
                'condition' => 'used-excellent',
                'original_price' => '17000000',
                'features' => 'Touchscreen, 2-in-1 Convertible, Gorilla Glass',
                'extras' => 'Tas Laptop',
            ],
            'category_id' => 2,
        ]);

        // === STORAGE SOLUTIONS & ACCESSORIES (Category ID: 9) === //
        
        Product::create([
            'name' => 'TP-Link USB 3.0 Type-C Card Reader UA430C',
            'brand' => 'TP-Link',
            'description' => 'Card reader premium dari TP-Link dengan USB Type-C 3.0 untuk transfer data super cepat hingga 200 MB/s. Mendukung SD dan microSD card sampai 2TB. Body aluminum alloy yang kokoh dengan kabel braided 15cm. Compatible dengan semua sistem operasi.',
            'price' => 100000,
            'sku' => 'DB-TPLINK-UA430C',
            'image_url' => 'https://images.unsplash.com/photo-1625948515291-69613efd103f?auto=format&fit=crop&q=80&w=800',
            'image_thumbnail_url' => 'https://images.unsplash.com/photo-1625948515291-69613efd103f?auto=format&fit=crop&q=80&w=400',
            'stock' => 5,
            'specifications' => [
                'product_number' => 'UA430C',
                'interface' => 'USB 3.0 Type-C, 5Gbps',
                'sd_slot' => 'SD Card (UHS-I, up to 200 MB/s, 2TB Max)',
                'microsd_slot' => 'microSD/TF (UHS-I, up to 200 MB/s, 2TB Max)',
                'compatibility' => 'Windows, MacOS, iPadOS, iOS, Android, Linux, Chrome OS',
                'material' => 'Aluminum Alloy Case',
                'cable' => '150mm (5.9 inch) Braided Cable',
                'dimensions_width' => '4.84',
                'dimensions_depth' => '3.42',
                'dimensions_height' => '1.15',
                'weight' => '28g',
                'certification' => 'CE, FCC, RoHS, BSMI',
                'warranty' => 'Garansi resmi TP-Link',
                'condition' => 'new',
                'extras' => 'Ready Stock • Cocok untuk photographer & videographer',
            ],
            'category_id' => 9,
        ]);
    }
}
